// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TodoAPI.Infrastructures.Data.Entities;

namespace TodoAPI.Infrastructures.Data;

public partial class LabContext : DbContext
{
    public LabContext(DbContextOptions<LabContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Todo> Todo { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Todo>(entity =>
        {
            entity.Property(e => e.TodoId).HasComment("PK");
            entity.Property(e => e.AddTime)
                .HasComment("新增時間")
                .HasColumnType("datetime");
            entity.Property(e => e.AddUserId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("新增者");
            entity.Property(e => e.CompleteTime)
                .HasComment("完成時間")
                .HasColumnType("datetime");
            entity.Property(e => e.IsComplete)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasComment("是否完成 (Y/N)")
                .HasDefaultValue("N", "DF_Todo_IsComplete");
            entity.Property(e => e.TodoContent)
                .HasMaxLength(500)
                .HasComment("待辦內容");
            entity.Property(e => e.TodoTitle)
                .HasMaxLength(100)
                .HasComment("待辦標題");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("帳號");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
