// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace TodoAPI.Infrastructures.Data.Entities;

public partial class Todo
{
    /// <summary>
    /// PK
    /// </summary>
    public long TodoId { get; set; }

    /// <summary>
    /// 待辦標題
    /// </summary>
    public string TodoTitle { get; set; } = null!;

    /// <summary>
    /// 待辦內容
    /// </summary>
    public string? TodoContent { get; set; }

    /// <summary>
    /// 是否完成 (Y/N)
    /// </summary>
    public string IsComplete { get; set; } = null!;

    /// <summary>
    /// 完成時間
    /// </summary>
    public DateTime? CompleteTime { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime? AddTime { get; set; }

    /// <summary>
    /// 新增者
    /// </summary>
    public string AddUserId { get; set; } = null!;
}
