// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace TodoAPI.Infrastructures.Data.Entities;

public partial class User
{
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 帳號
    /// </summary>
    public string Password { get; set; } = null!;

    /// <summary>
    /// 角色
    /// </summary>
    public string Role { get; set; } = null!;
}
